# https://docs.travis-ci.com/user/deployment/npm/
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
addons:
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

deploy:
  provider: npm
  skip-cleanup: true
  email: "852835915@qq.com"
  # api_key: "$NPM_TOKEN"
  token: $GH_TOKEN
  keep_history: true
  target_branch: master